### ISSUE TITLE
README.md file needs to be updated

### ISSUE THREAD

**Issue by li-clement** [OpenDataology/OpenDataology#7]

**Comment by ZichengQu** [comment]
This is the candidate name list for our dataset metadata and license compliance. If you have any ideas or names, feel free to suggest them. Please take a look and vote for your best two favorite ones.

<html>
<body>
<!DOCTYPE html><figure class="md-table-fig" cid="n101" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

No. | Name | Full name | Reason | Naming reference | Is repeated (searching via  Google)
-- | -- | -- | -- | -- | --
1 | BytesCompliance | Bytes compliance | Bytes can stand for data-related  field which should be suitable. | OpenBytes | Compliance Bytes can be searched via Google.
2 | DATAology | - | - | FOSSology and OpenJudge | A little general, and can be searched via Google.
3 | openDL4PL | Open dataset license for  provenance and lineage | Can highlight the main technical  means. | OpenDS4All | No
4 | openLicense4DS | Open license for dataset | - | OpenBytes、OpenLineage 和  OpenDS4All | No
5 | BytesCornerstone | Bytes cornerstone | Dataset license compliance  project is a Cornerstone, a base that can support how people can use dataset  correctly. |   | No
6 | DataCornerstone | Data cornerstone | Just use data instead of bytes directly. |   | Cornerstone Data can be searched via Google.
7 | openLicense | Open license | Highlight license. | OpenBytes、OpenLineage | Should be a term name, but not a project name.
8 | DMLCPractice | Practice for dataset metadata and license compliance | Use the full name. | Datapractices.org | There is DMLC from Google, but  DMLCPractice is not found.
9 | Comply | - | - | - | Yes
10 | openDLC | Open dataset license compliance | Project purpose. | OpenDS4All | Repeated
11 | openDUC | Open dataset usage corrector | Correct the way datasets are  used to avoid non-compliance issues. | OpenDS4All | Repeated
12 | openDUG | Open dataset usage guide | Guide users in the proper use of datasets. | OpenDS4All | Repeated
13 | CompliancePractice | Compliance practice | Highlight compliance. | Datapractices.org | Repeated

</figure><br class="Apple-interchange-newline">
</body>
</html>

**Comment by ZichengQu** [comment]
The PR of an initial README.md is waiting for a review by @rgopikrishnan91 to make a final version, then this issue can be closed. The link is https://github.com/BytesCompliance/BytesCompliance/pull/16

**Comment by rgopikrishnan91** [comment]
Done, looks good. Closing this issue
